### PR TITLE
added typescript typings to the project

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
* added a file called `index.d.ts`
* added the `typings` key into `package.json` so that Typescript will pick up the `index.d.ts` automatically

### CODE REVIEW

**Comment by twhiteman** [comment]
Thanks!

**Comment by YashdalfTheGray** [comment]
@twhiteman if I can ask, what's the release cycle like for this node package? I'm not blocked because it's used in a personal project but I was just wondering when I could pick the project back up with the version that has the typings on it. 

I also don't mean to imply that you should rush on it 🙂

**Comment by twhiteman** [comment]
It's fairly slow release cycle (on demand), so I just pushed your changes in the 1.0.3 release.

**Comment by YashdalfTheGray** [comment]
Thanks so much!

**Pull request merged**
